export const createToDoEntry = async (body) => {
  try {
  } catch (err) {
    console.log("error occured in create todo entry -->", err);
    throw new Error(err);
  }
};

export const editToDoEntry = async (body) => {
  try {
  } catch (err) {
    console.log("error occured in edit todo entry -->", err);
    throw new Error(err);
  }
};

export const deleteToDoEntry = async (body) => {
  try {
  } catch (err) {
    console.log("error occured in delete todo entry -->", err);
    throw new Error(err);
  }
};

export const getToDoEntry = async (body) => {
  try {
  } catch (err) {
    console.log("error occured in get todo entry -->", err);
    throw new Error(err);
  }
};

export const getAllToDoEntries = async (body) => {
  try {
  } catch (err) {
    console.log("error occured in get all todo entries -->");
    throw new Error(err);
  }
};
