export const createUser = async (body) => {
  try {
  } catch (err) {
    console.log("error occured in create user --> ", err);
    throw new Error(err);
  }
};

export const loginUser = async (body) => {
  try {
  } catch (err) {
    console.log("error occured in login user -->", err);
    throw new Error(err);
  }
};

export const signupUser = async (body) => {
  try {
  } catch (err) {
    console.log("error occured in signup user -->", err);
    throw new Error(err);
  }
};

export const logoutUser = async (body) => {
  try {
  } catch (err) {
    console.log("error occured in logout user -->", err);
    throw new Error(err);
  }
};

export const refreshToken = async (body) => {
  try {
  } catch (err) {
    console.log("error occured in refresh token -->", err);
    throw new Error(err);
  }
};
